# Generated by Django 6.0.1 on 2026-02-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BridgeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_project_id", models.BigIntegerField(unique=True)),
                (
                    "git_provider",
                    models.CharField(
                        choices=[("gitlab", "GitLab"), ("github", "GitHub")],
                        max_length=20,
                    ),
                ),
                ("git_repo", models.CharField(max_length=255)),
                ("default_base_branch", models.CharField(default="dev", max_length=120)),
                ("main_branch", models.CharField(default="main", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bridge_link",
                "indexes": [
                    models.Index(
                        fields=["git_provider", "git_repo"],
                        name="bridge_link_git_pro_3a5705_idx",
                    ),
                    models.Index(fields=["is_active"], name="bridge_link_is_acti_1fdbb1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BridgeTaskSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odoo_task_id", models.BigIntegerField(unique=True)),
                ("odoo_project_id", models.BigIntegerField()),
                ("git_branch", models.CharField(max_length=255)),
                ("git_base_branch", models.CharField(max_length=120)),
                ("mr_id", models.CharField(blank=True, max_length=120, null=True)),
                ("mr_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("branch_created", "Branch Created"),
                            ("mr_opened", "MR Opened"),
                            ("changes_requested", "Changes Requested"),
                            ("approved", "Approved"),
                            ("merged_dev", "Merged Dev"),
                            ("merged_main", "Merged Main"),
                            ("closed", "Closed"),
                        ],
                        default="branch_created",
                        max_length=30,
                    ),
                ),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bridge_tasksync",
                "indexes": [
                    models.Index(
                        fields=["odoo_project_id"],
                        name="bridge_task_odoo_pr_4425b8_idx",
                    ),
                    models.Index(fields=["status"], name="bridge_task_status_b8878b_idx"),
                    models.Index(
                        fields=["last_event_at"],
                        name="bridge_task_last_ev_aaecd1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BridgeWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("gitlab", "GitLab"), ("github", "GitHub")],
                        max_length=20,
                    ),
                ),
                ("event_type", models.CharField(max_length=80)),
                ("event_id", models.CharField(blank=True, max_length=255, null=True)),
                ("signature_ok", models.BooleanField(default=False)),
                ("payload", models.JSONField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bridge_webhookevent",
                "indexes": [
                    models.Index(
                        fields=["provider", "event_type"],
                        name="bridge_webh_provide_f52fa1_idx",
                    ),
                    models.Index(fields=["received_at"], name="bridge_webh_receive_e4a882_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("event_id__isnull", False)),
                        fields=("provider", "event_id"),
                        name="uq_bridge_webhookevent_provider_event_id",
                    )
                ],
            },
        ),
    ]
